// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Shippings.Infrastructure.Context.ShippingMethods;

#nullable disable

namespace Modules.Shippings.Infrastructure.Migrations.ShippingMethodsDb
{
    [DbContext(typeof(ShippingMethodsDbContext))]
    [Migration("20230806144928_ShippingMethodsInitMigration")]
    partial class ShippingMethodsInitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Modules.Shippings.Domain.Entities.ShippingMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationTimeInDays")
                        .HasColumnType("int")
                        .HasColumnName("DurationTimeInDays");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit")
                        .HasColumnName("IsAvailable");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShippingMethods", (string)null);
                });

            modelBuilder.Entity("Modules.Shippings.Domain.Entities.ShippingMethod", b =>
                {
                    b.OwnsOne("Shared.Domain.ValueObjects.MoneyValue", "BasePrice", b1 =>
                        {
                            b1.Property<Guid>("ShippingMethodId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("BaseAmount");

                            b1.Property<string>("Currency")
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("BaseCurrency");

                            b1.HasKey("ShippingMethodId");

                            b1.ToTable("ShippingMethods");

                            b1.WithOwner()
                                .HasForeignKey("ShippingMethodId");
                        });

                    b.Navigation("BasePrice");
                });
#pragma warning restore 612, 618
        }
    }
}
